// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-BxqPeWwNwJGDCTdmiNjIU7vgOaNfKCo',
    appId: '1:722993153540:web:2b09854f21567173c09751',
    messagingSenderId: '722993153540',
    projectId: 'heart-iq-59cbe',
    authDomain: 'heart-iq-59cbe.firebaseapp.com',
    storageBucket: 'heart-iq-59cbe.firebasestorage.app',
    measurementId: 'G-Q2RF9JYF4Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaeSgxhgEDA5tr4-Gtc_Hh70Vo-tLlnvY',
    appId: '1:722993153540:android:1e4c8f01e56eae78c09751',
    messagingSenderId: '722993153540',
    projectId: 'heart-iq-59cbe',
    storageBucket: 'heart-iq-59cbe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgLgOlE_aGikD_XX2G23_88xLbyi52g70',
    appId: '1:722993153540:ios:941467504b05d0c7c09751',
    messagingSenderId: '722993153540',
    projectId: 'heart-iq-59cbe',
    storageBucket: 'heart-iq-59cbe.firebasestorage.app',
    iosBundleId: 'com.example.heartIq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgLgOlE_aGikD_XX2G23_88xLbyi52g70',
    appId: '1:722993153540:ios:941467504b05d0c7c09751',
    messagingSenderId: '722993153540',
    projectId: 'heart-iq-59cbe',
    storageBucket: 'heart-iq-59cbe.firebasestorage.app',
    iosBundleId: 'com.example.heartIq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-BxqPeWwNwJGDCTdmiNjIU7vgOaNfKCo',
    appId: '1:722993153540:web:fc9c7f714222bfc9c09751',
    messagingSenderId: '722993153540',
    projectId: 'heart-iq-59cbe',
    authDomain: 'heart-iq-59cbe.firebaseapp.com',
    storageBucket: 'heart-iq-59cbe.firebasestorage.app',
    measurementId: 'G-XS3QJF26WJ',
  );
}
